### ISSUE TITLE
Deleting produces -> Fatal error: Cannot redeclare class tl_fd_voting in <...>/system/modules/efg/dca/fd_voting.php on line 0

### ISSUE THREAD

**Issue by Defcon0** [1up-lab/contao-efg#4]
Hello,

deleting records leads to the issue above. According to Google, it seems to be a known issue possibly fixable by https://bitbucket.org/thk/efg/issues/83/fatal-error-cannot-redeclare-class

Do you have any idea on that?

Bye Defcon0

**Comment by bytehead** [comment]
Hi Defcon0

We are actually have no support for this extension. It's just a packagist mirror for our old installations that use EFG. I would you suggest to change your installation to [contao-leads](https://github.com/terminal42/contao-leads).

Otherwise you can provide a PR, which we can easily merge.
